SpionShopWebsite/ViewModels/ArtikelViewModel.cs
using SpionshopLib;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SpionShopWebsite.ViewModels
{
   public class ArtikelViewModel
    {
        public List<Artikel> artikel { get; set; }
        public string com { get; set; }
        public string afl { get; set; }
        public string alg { get; set; }
    }
}

SpionShopWebsite/Controllers/ArtikelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SpionshopLib;
using SpionShopWebsite.Models;
using SpionShopWebsite.Areas.Admin.Controllers;
using System.Net.Http;
using Newtonsoft.Json;
using SpionshopWebAPI.Models;
using SpionshopWebAPI.Models.Proxies;
using AutoMapper;
using AutoMapper.QueryableExtensions;

namespace SpionShopWebsite
{
    public class ArtikelsController : Controller
    {
        private SpionshopEntities db = new SpionshopEntities();
        private decimal? totaal;

        // GET: Artikels
        public async Task<ActionResult> Index()
        {
            //WinkelWagen ww = new WinkelWagen();
            //// ww.GetCart(this,ww);
            //ww.GetCart(this);

            //var artikel = db.Artikel.Include(a => a.Categorie);
            //return View(await artikel.ToListAsync());

            string uri = "http://" + Request.Url.Host + ':' + Request.Url.Port + "/api/artikels";
            using (HttpClient httpClient = new HttpClient())
            {
                Task<String> response = httpClient.GetStringAsync(uri);

                return
                    View(
                            Task.Factory.StartNew
                            (
                                () => JsonConvert
                                        .DeserializeObject<List<ArtikelDTO>>(response.Result)
                            )
                            .Result
                         );
            }
        }

        // GET: Artikels/Details/5
        public async Task<ActionResult> Details(short? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            string uri = "http://" + Request.Url.Host + ':' + Request.Url.Port + "/api/artikels/" + id;
            using (HttpClient httpClient = new HttpClient())
            {
                Task<String> response = httpClient.GetStringAsync(uri);

                return
                    View(
                            Task.Factory.StartNew
                            (
                                () => JsonConvert
                                        .DeserializeObject<ArtikelDetailDTO>(response.Result)
                            )
                            .Result
                         );
            }
        
    }

        // GET: Artikels/Create
        public ActionResult Create()
        {
            ViewBag.Cat_id = new SelectList(db.Categorie, "Cat_id", "Categorie1");
            return View();
        }

        // POST: Artikels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Artikel_id,Cat_id,Artikel1,Omschrijving,Verkoopprijs,Instock")] ArtikelDTO artikelDTO)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<ArtikelDTO, Artikel>();
                Artikel artikel = Mapper.Map<Artikel>(artikelDTO);

                db.Artikel.Add(artikel);
                await db.SaveChangesAsync(); 
                return RedirectToAction("Index");
            }

            ViewBag.Cat_id = new SelectList(db.Categorie, "Cat_id", "Categorie1", artikelDTO.Artikel_id);
            return View(artikelDTO);
        }

        // GET: Artikels/Edit/5
        public async Task<ActionResult> Edit(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artikel artikel = await db.Artikel.FindAsync(id);
            if (artikel == null)
            {
                return HttpNotFound();
            }
            ViewBag.Cat_id = new SelectList(db.Categorie, "Cat_id", "Categorie1", artikel.Cat_id);
            return View(artikel);
        }

        // POST: Artikels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Artikel_id,Cat_id,Artikel1,Omschrijving,Verkoopprijs,Instock")] Artikel artikel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artikel).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Cat_id = new SelectList(db.Categorie, "Cat_id", "Categorie1", artikel.Cat_id);
            return View(artikel);
        }

        // GET: Artikels/Delete/5
        public async Task<ActionResult> Delete(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artikel artikel = await db.Artikel.FindAsync(id);
            if (artikel == null)
            {
                return HttpNotFound();
            }
            return View(artikel);
        }

        // POST: Artikels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(short id)
        {
            Artikel artikel = await db.Artikel.FindAsync(id);
            db.Artikel.Remove(artikel);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Artikels

        public async Task<ActionResult> Artikel(String naam)
        {

            UriBuilder baseUri = new UriBuilder("http://" + Request.Url.Host + ":" + Request.Url.Port + "/api/artikels?");
            string queryToAppend = naam;

            if (baseUri.Query != null)
                baseUri.Query = baseUri.Query.Substring(1) + queryToAppend;
            string uri = baseUri.ToString();

            using (HttpClient httpClient = new HttpClient())
            {

                Task<String> response = httpClient.GetStringAsync(uri);

                return
                    View(
                            Task.Factory.StartNew
                            (
                                () => JsonConvert
                                        .DeserializeObject<List<ArtikelDetailDTO>>(response.Result)
                            )
                            .Result
                         );
            }

        }

        public async Task<ActionResult> ArtikelPerCategorie(String naam)
        {
           
            
            UriBuilder baseUri = new UriBuilder("http://" + Request.Url.Host + ":" + Request.Url.Port + "/api/artikels?");
            string queryToAppend = "categorienaam=" + naam;
            if (baseUri.Query != null)
                baseUri.Query = baseUri.Query.Substring(1) + queryToAppend;
            string uri = baseUri.ToString();
           
            using (HttpClient httpClient = new HttpClient())
            {
                Task<String> response = httpClient.GetStringAsync(uri);
                return
                    View(
                        Task.Factory.StartNew
                        (
                            () => JsonConvert
                                .DeserializeObject<List<ArtikelDetailDTO>>(response.Result)
                         )
                            .Result
                         );
                 }
            }



        public async Task<ActionResult> Detail(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var artikel = db.Artikel.Where(c => c.Artikel_id == id);
            return View(await artikel.ToListAsync());
        }
      
        public JsonResult GetCategories()
        {
            List<String> Categories = new List<string>();
            List<Categorie> categories = db.Categorie.ToList();
            foreach (Categorie c in categories) {
                Categories.Add(c.Categorie1);
                    }
       
            return Json(new { lcat=Categories });
        }

        
        [HttpPost]
        public ActionResult UpdateWinkelMand(string textBox1,string name,bool aanpassing)
        //public String UpdateWinkelMand(string textBox1, string name, bool aanpassing)
        {
            
            short id = Int16.Parse(name);
            Artikel artikel = db.Artikel.Find(id);

            //checken of er al een winkelmand bestaat voor huidige sessie, indien niet maak er een aan
            WinkelWagen ww = new WinkelWagen();
               ww= ww.GetCart(this, ww);

           // voeg artikel toe aan winkelmand of pas hoeveelheid aan
            if (aanpassing)
            {
                ww.PasBestelingAan(artikel, short.Parse(textBox1), ww);
            }

            else { 
           ww.AddToCart(artikel, short.Parse(textBox1),ww);
           TempData["succesboodschap"] = "Winkelmand gevuld met " +textBox1+ " " + artikel.Artikel1;
                    }
            return JavaScript("document.location.replace('" + Url.Action("Index") + "');");

        }

        public JsonResult UpdateWinkelMandje(BestellingDetailDTO lijn)
        {
          
            Artikel artikel = db.Artikel.Find(lijn.Artikel_id);
            WinkelWagen ww = new WinkelWagen();
            ww = ww.GetCart(this, ww);
            ww.PasBestelingAan(artikel,lijn.Aantal, ww);
            return Json(new  { aantal = lijn.Aantal, totaal=artikel.Verkoopprijs*lijn.Aantal,benaming=artikel.Artikel1});
            
        }

        protected override void Dispose(bool disposing)
        {

SpionShopWebsite/Views/Artikels/ArtikelPerCategorie.cshtml
@using SpionshopWebAPI.Models
@model List<ArtikelDetailDTO>

@{
    ViewBag.Title = "ArtikelPerCategorie";
}

<div>
             @foreach (ArtikelDetailDTO a in Model)
               {
                <img src="@Html.ImageUrlFor("~/Content/Images/thumbs/"+@a.Artikel_id+".gif")" height="100" />
                @*<img src="@Url.Content("~/Content/Images/thumbs/"+@a.Artikel_id+".gif")" />*@
                <dl class="dl-horizontal">
                    <dt>
                        Artikel
                    </dt>
                    <dd>
                        @Html.ActionLink(@a.Artikel1, "Detail", new {id = @a.Artikel_id },null)
                 </dd>
                    <dt>
                        Verkoopprijs
                    </dt>

                    <dd>
                        @Html.DisplayFor(t => a.Verkoopprijs)
                    </dd>
                </dl>
            }

</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

SpionShopWebsite/Views/Artikels/Create.cshtml
@model SpionshopLib.Artikel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Artikel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cat_id, "Cat_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cat_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cat_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Artikel1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Artikel1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Artikel1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Omschrijving, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Omschrijving, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Omschrijving, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Verkoopprijs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Verkoopprijs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Verkoopprijs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Instock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Instock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SpionShopWebsite/Views/Artikels/Delete.cshtml
@model SpionshopLib.Artikel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Artikel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artikel1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artikel1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Omschrijving)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Omschrijving)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Verkoopprijs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Verkoopprijs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categorie.Categorie1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie.Categorie1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SpionShopWebsite/Views/Artikels/Detail.cshtml
@model IEnumerable < SpionshopLib.Artikel >
@*@model SpionshopLib.Artikel*@ 

@{
    ViewBag.Title = "Detail";

}


<h2>Detail</h2>
@{
    AjaxOptions options = new AjaxOptions();
    options.HttpMethod = "POST";
    options.UpdateTargetId = "divResponse";
    options.InsertionMode = InsertionMode.Replace;
}

@using (Ajax.BeginForm("UpdateWinkelMand", "Artikels", options))
{
    <table id="PasAan" class="table">
        <tr>
            <th>
                <br />
               Afbeelding
            </th>
            <th>
                <br />
                @*@Html.DisplayNameFor(model => model.Artikel1)*@
                Naam
            </th>
            <th>
                <br />
                @Html.DisplayNameFor(model => model.Omschrijving)
            </th>
            <th>
                <br />
                @Html.DisplayNameFor(model => model.Verkoopprijs)
            </th>
           
            <th>
                <img alt="winkelmand" height="42" width="42" src="@Url.Content("~/Content/Images/winkelmandje.png")" />
                Aantal in winkelmandje
            </th>
        </tr>
        
       @foreach (var item in Model)
       {
         
           
            <tr>
                <td>
                    <img src="@Html.ImageUrlFor("~/Content/Images/Big/"+@Html.DisplayFor(modelItem =>item.Artikel_id)+".gif")" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Artikel1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Omschrijving)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Verkoopprijs)
                </td>
                
                                <td id="aantalBesteld">
         
                                    @{string test = Model.First().Artikel_id.ToString();
                                        @Html.Hidden("Name", test);
                                        bool aanpassing = false;
                                        @Html.Hidden("aanpassing", aanpassing);
                                    }
       
           @Html.TextBox("textBox1")
           
    </td>
                
                
                <td>
                    
                
               
                    
                    <input type="submit"  value="Voeg toe" />
                    
                </td>

            </tr>
        }
    </table>
}


@Html.ActionLink("Terug naar lijst", "index")
<div id="divResponse"></div>

SpionShopWebsite/Views/Artikels/Details.cshtml
@*@model SpionshopLib.Artikel*@
@using SpionshopWebAPI.Models
@model  ArtikelDetailDTO

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Artikel</h4>
    <hr />
    @*<dl class="dl-horizontal">*@
    @*<dt>
                @Html.DisplayNameFor(model => model.Artikel1)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Artikel1)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Omschrijving)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Omschrijving)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Verkoopprijs)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Verkoopprijs)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Instock)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Instock)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Categorie.Categorie1)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Categorie.Categorie1)
            </dd>

        </dl>*@
    @*@foreach (var item in Model)
    {*@
        
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model=>model.Artikel1)
            </dt>

            <dd>
                    @Html.DisplayFor(model=>model.Artikel1)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Omschrijving)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Omschrijving)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Verkoopprijs)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Verkoopprijs)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Instock)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Instock)
                </dd>

                @*<dt>
                    @Html.DisplayNameFor(model => model.Categorie.Categorie1)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Categorie.Categorie1)
                </dd>*@

        </dl>
    @*}*@
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Artikel_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SpionShopWebsite/Views/Artikels/Edit.cshtml
@model SpionshopLib.Artikel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Artikel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Artikel_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Cat_id, "Cat_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Cat_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cat_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Artikel1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Artikel1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Artikel1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Omschrijving, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Omschrijving, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Omschrijving, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Verkoopprijs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Verkoopprijs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Verkoopprijs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Instock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Instock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SpionShopWebsite/Views/Artikels/Index.cshtml
@*@model IEnumerable<SpionshopLib.Artikel>*@
@using SpionshopWebAPI.Models
@model List<ArtikelDTO>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>Naam</th>
        <th>Omschrijving</th>
        <th></th>
    </tr>

@foreach (ArtikelDTO artikelDTO in Model) {
    <tr>
        <td class="test" data-id="@artikelDTO.Artikel_id">
            @Html.DisplayFor(modelItem => artikelDTO.Artikel1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => artikelDTO.Omschrijving)
                                                               
        </td>
<td hidden>
    <img id="@Html.DisplayFor(modelitem =>artikelDTO.Artikel_id)"src="@Html.ImageUrlFor("~/Content/Images/Big/"+@Html.DisplayFor(modelitem =>artikelDTO.Artikel_id)+".gif")" />
</td>
        <td>
@*@Html.ActionLink("Details", "Details", new { id=item.Artikel_id }) |*@
            @Html.ActionLink("Bestel", "Detail", new { id= artikelDTO.Artikel_id })
        </td>
    </tr>
}

</table>
<!-- Bootstrap Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h4 class="modal-title" id="myModalLabel">Artikel detail</h4>
            </div>
            
            <div  class="modal-body">
               
                
            </div>
            
          <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Sluiten</button>
               
            </div>
        </div>
    </div>
</div>

<div id="foo">
</div>



    <script>
        $(document).ready(function () {
            var url = 'http://' + window.location.host + '/api/artikels/';
            var infoModal = $('#myModal');
            $(function () {
                $('td.test').css('cursor', 'pointer').click(function () {

                    $.ajax({
                     
                        type: "GET",
                        url: url + $(this).data('id'),
                        header :'Access-Control-Allow-Origin',
                        dataType: 'json',
                        success: function (data) {
                            var htmlData = '<h4>' + data.Artikel1 + '</h4><hr>';
                            htmlData += '<br><p>Omschrijving: ' + data.Omschrijving + '</p>';
                            htmlData += '<br><p>Prijs: ' + data.Verkoopprijs + '</p>';
                            htmlData += '<br><p>In stock: ' + data.Instock + '</p>';



                            var id = data.Artikel_id
                            var vervang="new{id="+id+"}"
                            var test = "location.href='@Url.Action("Detail", "Artikels", new { id = 1 })'"
                            var ok = test.replace("1", id);


                            var r = $('<input/>').attr({
                                type: "button",
                                id: "field",
                                value: 'Bestel',
                                class: "btn btn-default",
                                data: { dismiss: "modal" },
                                onclick:ok
                            });
                            $(".modal-footer").append(r);
                            infoModal.find('.modal-body').html(htmlData);

                            infoModal.modal('show');
                        },
                        error: function (XMLHttpRequest, textStatus, errorThrown) {
                            alert("click mislukt");
                            var err = eval("(" + XMLHttpRequest.responseText + ")");
                            alert("Status: " + textStatus); alert("Error: " + err.Message);
                        }

                    });
                });
            });
            
        });
    </script>